## Helm Style Dataset Generation

In [2]:
import pandas as pd
import re
import requests

In [4]:
df = pd.read_csv("../data/challenge_data/clinicalnlp_taskB_test1.csv")
df.head()

,dataset,encounter_id,dialogue,note
0,virtassist,D2N088,"[doctor] hi , andrew . how are you ?\n[patient...",CHIEF COMPLAINT\n\nUpper respiratory infection...
1,virtassist,D2N089,"[doctor] hi andrea , how are you ?\n[patient] ...",CHIEF COMPLAINT\n\nAnnual exam.\n\nHISTORY OF ...
2,virtassist,D2N090,"[doctor] hi , albert . how are you ?\n[patient...",CHIEF COMPLAINT\n\nER follow-up.\n\nHISTORY OF...
3,virtassist,D2N091,"[doctor] hi jerry , how are you doing ?\n[pati...",CHIEF COMPLAINT\n\nAnnual exam.\n\nHISTORY OF ...
4,virtassist,D2N092,"[doctor] hello , mrs . martinez . good to see ...",CC:\n\nRight arm pain.\n\nHPI:\n\nMs. Martinez...

In [ ]:
# find instances of query words that are almost always followed by drug/therapy names
query_words = r'\b(prescribe|prescribed|initiate)\b'
mask = df['note'].str.contains(query_words, case=False, regex=True)
filtered_df = df[mask].copy()

def find_match_indices(text):
    return [m.start() for m in re.finditer(query_words, text, flags=re.IGNORECASE)]

filtered_df['match_indices'] = filtered_df['note'].apply(find_match_indices)
filtered_df

/var/folders/95/v1w_5gps1tv7kdq9zxkwrb980000gn/T/ipykernel_60251/608396341.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = df['note'].str.contains(query_words, case=False, regex=True)

,dataset,encounter_id,dialogue,note,match_indices
5,virtassist,D2N093,[doctor] hey lawrence . how are you ?\n[patien...,CHIEF COMPLAINT\n\nShortness of breath.\n\nHIS...,[2878]
7,virtassist,D2N095,"[doctor] hi , cheryl . how are you ?\n[patient...",CHIEF COMPLAINT\n\nBack pain.\n\nHISTORY OF PR...,[2154]
9,virtassist,D2N097,"[doctor] elizabeth , how are you ?\n[patient] ...",CHIEF COMPLAINT\n\nAnnual exam.\n\nHISTORY OF ...,[983]
17,virtscribe,D2N105,[doctor] patient's name is diana scott . date ...,CHIEF COMPLAINT\n\nHeart murmur.\n\nHISTORY OF...,[815]
18,aci,D2N106,[doctor] hey charles i'm using this cool new r...,CHIEF COMPLAINT\n\nShortness of breath.\n\nHIS...,"[506, 1898]"
20,aci,D2N108,[doctor] hey gregory good to see you today so ...,CHIEF COMPLAINT\n\nRight foot ulcer.\n\nHISTOR...,[441]
22,aci,D2N110,[doctor] okay hi wayne well i understand you'r...,HISTORY OF PRESENT ILLNESS\n\nWayne Jenkins is...,[2545]
23,aci,D2N111,[doctor] hey william so i see that you injured...,CHIEF COMPLAINT\n\nRight knee injury.\n\nHISTO...,"[1294, 2095]"
31,aci,D2N119,[doctor] hey betty how are you doing\n[patient...,CHIEF COMPLAINT\n\nAsthma.\n\nMEDICAL HISTORY\...,[1708]
32,aci,D2N120,[doctor] hello larry how are you doing today\n...,HISTORY OF PRESENT ILLNESS\n\nLarry Garcia is ...,[943]
35,aci,D2N123,[doctor] so tyler is a 56 -year-old male who p...,SUBJECTIVE\n\nDifficulty swallowing. Tyler Gre...,[3207]
36,aci,D2N124,[doctor] so jerry is a 45 -year-old male who c...,CHIEF COMPLAINT\n\nRight ankle injury.\n\nHIST...,[1951]
39,aci,D2N127,[doctor] hey brandon you know glad to see you ...,CHIEF COMPLAINT\n\nNeck pain.\n\nHISTORY OF PR...,"[680, 2032]"

In [ ]:
# verify the extracted indices are correct
def extract_words_at_indices(text, indices):
    words = []
    for idx in indices:
        # Find the word that includes the character at index `idx`
        match = re.search(r'\b\w+\b', text[idx:])
        if match and match.start() == 0:
            words.append(match.group())
    return words

filtered_df['matched_words'] = filtered_df.apply(lambda row: extract_words_at_indices(row['note'], row['match_indices']), axis=1)
filtered_df

,dataset,encounter_id,dialogue,note,match_indices,matched_words
5,virtassist,D2N093,[doctor] hey lawrence . how are you ?\n[patien...,CHIEF COMPLAINT\n\nShortness of breath.\n\nHIS...,[2878],[Initiate]
7,virtassist,D2N095,"[doctor] hi , cheryl . how are you ?\n[patient...",CHIEF COMPLAINT\n\nBack pain.\n\nHISTORY OF PR...,[2154],[initiate]
9,virtassist,D2N097,"[doctor] elizabeth , how are you ?\n[patient] ...",CHIEF COMPLAINT\n\nAnnual exam.\n\nHISTORY OF ...,[983],[prescribed]
17,virtscribe,D2N105,[doctor] patient's name is diana scott . date ...,CHIEF COMPLAINT\n\nHeart murmur.\n\nHISTORY OF...,[815],[prescribed]
18,aci,D2N106,[doctor] hey charles i'm using this cool new r...,CHIEF COMPLAINT\n\nShortness of breath.\n\nHIS...,"[506, 1898]","[prescribed, prescribed]"
20,aci,D2N108,[doctor] hey gregory good to see you today so ...,CHIEF COMPLAINT\n\nRight foot ulcer.\n\nHISTOR...,[441],[prescribed]
22,aci,D2N110,[doctor] okay hi wayne well i understand you'r...,HISTORY OF PRESENT ILLNESS\n\nWayne Jenkins is...,[2545],[prescribed]
23,aci,D2N111,[doctor] hey william so i see that you injured...,CHIEF COMPLAINT\n\nRight knee injury.\n\nHISTO...,"[1294, 2095]","[prescribed, prescribe]"
31,aci,D2N119,[doctor] hey betty how are you doing\n[patient...,CHIEF COMPLAINT\n\nAsthma.\n\nMEDICAL HISTORY\...,[1708],[Prescribed]
32,aci,D2N120,[doctor] hello larry how are you doing today\n...,HISTORY OF PRESENT ILLNESS\n\nLarry Garcia is ...,[943],[prescribed]
35,aci,D2N123,[doctor] so tyler is a 56 -year-old male who p...,SUBJECTIVE\n\nDifficulty swallowing. Tyler Gre...,[3207],[prescribed]
36,aci,D2N124,[doctor] so jerry is a 45 -year-old male who c...,CHIEF COMPLAINT\n\nRight ankle injury.\n\nHIST...,[1951],[prescribe]
39,aci,D2N127,[doctor] hey brandon you know glad to see you ...,CHIEF COMPLAINT\n\nNeck pain.\n\nHISTORY OF PR...,"[680, 2032]","[prescribed, prescribed]"

In [ ]:
# truncate note at each instance of query word - one note can produce multiple truncated versions 
def truncate_and_extract(note, indices, query_words):
    truncated_notes = []
    deleted_starts = []

    for idx in indices:
        # Extend to end of matched word
        match = re.search(query_words, note[idx:], flags=re.IGNORECASE)
        if not match:
            continue
        end_of_match = idx + match.end()

        # Truncate note at end of match
        truncated = note[:end_of_match].strip()

        # Deleted part starts here
        deleted_part = note[end_of_match:].strip()

        # Get first sentence from deleted part
        first_sentence_match = re.search(r'(.+?[.!?])(\s|$)', deleted_part)
        first_sentence = first_sentence_match.group(1).strip() if first_sentence_match else ''

        # Store
        truncated_notes.append(truncated)
        deleted_starts.append(first_sentence)

    return truncated_notes, deleted_starts

query_words = r'\b(prescribe|prescribed|initiate)\b'

filtered_df['truncated_notes'] = filtered_df.apply(
    lambda row: truncate_and_extract(row['note'], row['match_indices'], query_words)[0], axis=1
)

filtered_df['deleted_first_sentences'] = filtered_df.apply(
    lambda row: truncate_and_extract(row['note'], row['match_indices'], query_words)[1], axis=1
)

filtered_df

,dataset,encounter_id,dialogue,note,match_indices,matched_words,truncated_notes,deleted_first_sentences
5,virtassist,D2N093,[doctor] hey lawrence . how are you ?\n[patien...,CHIEF COMPLAINT\n\nShortness of breath.\n\nHIS...,[2878],[Initiate],[CHIEF COMPLAINT\n\nShortness of breath.\n\nHI...,[Lasix 40 mg a day.]
7,virtassist,D2N095,"[doctor] hi , cheryl . how are you ?\n[patient...",CHIEF COMPLAINT\n\nBack pain.\n\nHISTORY OF PR...,[2154],[initiate],[CHIEF COMPLAINT\n\nBack pain.\n\nHISTORY OF P...,[meloxicam 15 mg once daily.]
9,virtassist,D2N097,"[doctor] elizabeth , how are you ?\n[patient] ...",CHIEF COMPLAINT\n\nAnnual exam.\n\nHISTORY OF ...,[983],[prescribed],[CHIEF COMPLAINT\n\nAnnual exam.\n\nHISTORY OF...,[The patient endorses nasal congestion.]
17,virtscribe,D2N105,[doctor] patient's name is diana scott . date ...,CHIEF COMPLAINT\n\nHeart murmur.\n\nHISTORY OF...,[815],[prescribed],[CHIEF COMPLAINT\n\nHeart murmur.\n\nHISTORY O...,[pain medicine.]
18,aci,D2N106,[doctor] hey charles i'm using this cool new r...,CHIEF COMPLAINT\n\nShortness of breath.\n\nHIS...,"[506, 1898]","[prescribed, prescribed]",[CHIEF COMPLAINT\n\nShortness of breath.\n\nHI...,"[an inhaler, which he uses when his symptoms a..."
20,aci,D2N108,[doctor] hey gregory good to see you today so ...,CHIEF COMPLAINT\n\nRight foot ulcer.\n\nHISTOR...,[441],[prescribed],[CHIEF COMPLAINT\n\nRight foot ulcer.\n\nHISTO...,"[antibiotics, however, he has not started them..."
22,aci,D2N110,[doctor] okay hi wayne well i understand you'r...,HISTORY OF PRESENT ILLNESS\n\nWayne Jenkins is...,[2545],[prescribed],[HISTORY OF PRESENT ILLNESS\n\nWayne Jenkins i...,[a collagenase ointment to be applied to the w...
23,aci,D2N111,[doctor] hey william so i see that you injured...,CHIEF COMPLAINT\n\nRight knee injury.\n\nHISTO...,"[1294, 2095]","[prescribed, prescribe]",[CHIEF COMPLAINT\n\nRight knee injury.\n\nHIST...,"[Musculoskeletal: Reports right knee pain., me..."
31,aci,D2N119,[doctor] hey betty how are you doing\n[patient...,CHIEF COMPLAINT\n\nAsthma.\n\nMEDICAL HISTORY\...,[1708],[Prescribed],[CHIEF COMPLAINT\n\nAsthma.\n\nMEDICAL HISTORY...,[provided for Flovent 110 mcg 1 puff twice per...
32,aci,D2N120,[doctor] hello larry how are you doing today\n...,HISTORY OF PRESENT ILLNESS\n\nLarry Garcia is ...,[943],[prescribed],[HISTORY OF PRESENT ILLNESS\n\nLarry Garcia is...,"[pain medications, however they only provided ..."
35,aci,D2N123,[doctor] so tyler is a 56 -year-old male who p...,SUBJECTIVE\n\nDifficulty swallowing. Tyler Gre...,[3207],[prescribed],[SUBJECTIVE\n\nDifficulty swallowing. Tyler Gr...,[Prilosec 20 mg once a day.]
36,aci,D2N124,[doctor] so jerry is a 45 -year-old male who c...,CHIEF COMPLAINT\n\nRight ankle injury.\n\nHIST...,[1951],[prescribe],[CHIEF COMPLAINT\n\nRight ankle injury.\n\nHIS...,[meloxicam to reduce swelling.]
39,aci,D2N127,[doctor] hey brandon you know glad to see you ...,CHIEF COMPLAINT\n\nNeck pain.\n\nHISTORY OF PR...,"[680, 2032]","[prescribed, prescribed]",[CHIEF COMPLAINT\n\nNeck pain.\n\nHISTORY OF P...,"[fentanyl; however, he has not received a pres..."

In [6]:
filtered_df = filtered_df.reset_index()
filtered_df

,index,dataset,encounter_id,dialogue,note,match_indices,matched_words,truncated_notes,deleted_first_sentences
0,5,virtassist,D2N093,[doctor] hey lawrence . how are you ?\n[patien...,CHIEF COMPLAINT\n\nShortness of breath.\n\nHIS...,[2878],[Initiate],[CHIEF COMPLAINT\n\nShortness of breath.\n\nHI...,[Lasix 40 mg a day.]
1,7,virtassist,D2N095,"[doctor] hi , cheryl . how are you ?\n[patient...",CHIEF COMPLAINT\n\nBack pain.\n\nHISTORY OF PR...,[2154],[initiate],[CHIEF COMPLAINT\n\nBack pain.\n\nHISTORY OF P...,[meloxicam 15 mg once daily.]
2,9,virtassist,D2N097,"[doctor] elizabeth , how are you ?\n[patient] ...",CHIEF COMPLAINT\n\nAnnual exam.\n\nHISTORY OF ...,[983],[prescribed],[CHIEF COMPLAINT\n\nAnnual exam.\n\nHISTORY OF...,[The patient endorses nasal congestion.]
3,17,virtscribe,D2N105,[doctor] patient's name is diana scott . date ...,CHIEF COMPLAINT\n\nHeart murmur.\n\nHISTORY OF...,[815],[prescribed],[CHIEF COMPLAINT\n\nHeart murmur.\n\nHISTORY O...,[pain medicine.]
4,18,aci,D2N106,[doctor] hey charles i'm using this cool new r...,CHIEF COMPLAINT\n\nShortness of breath.\n\nHIS...,"[506, 1898]","[prescribed, prescribed]",[CHIEF COMPLAINT\n\nShortness of breath.\n\nHI...,"[an inhaler, which he uses when his symptoms a..."
5,20,aci,D2N108,[doctor] hey gregory good to see you today so ...,CHIEF COMPLAINT\n\nRight foot ulcer.\n\nHISTOR...,[441],[prescribed],[CHIEF COMPLAINT\n\nRight foot ulcer.\n\nHISTO...,"[antibiotics, however, he has not started them..."
6,22,aci,D2N110,[doctor] okay hi wayne well i understand you'r...,HISTORY OF PRESENT ILLNESS\n\nWayne Jenkins is...,[2545],[prescribed],[HISTORY OF PRESENT ILLNESS\n\nWayne Jenkins i...,[a collagenase ointment to be applied to the w...
7,23,aci,D2N111,[doctor] hey william so i see that you injured...,CHIEF COMPLAINT\n\nRight knee injury.\n\nHISTO...,"[1294, 2095]","[prescribed, prescribe]",[CHIEF COMPLAINT\n\nRight knee injury.\n\nHIST...,"[Musculoskeletal: Reports right knee pain., me..."
8,31,aci,D2N119,[doctor] hey betty how are you doing\n[patient...,CHIEF COMPLAINT\n\nAsthma.\n\nMEDICAL HISTORY\...,[1708],[Prescribed],[CHIEF COMPLAINT\n\nAsthma.\n\nMEDICAL HISTORY...,[provided for Flovent 110 mcg 1 puff twice per...
9,32,aci,D2N120,[doctor] hello larry how are you doing today\n...,HISTORY OF PRESENT ILLNESS\n\nLarry Garcia is ...,[943],[prescribed],[HISTORY OF PRESENT ILLNESS\n\nLarry Garcia is...,"[pain medications, however they only provided ..."
10,35,aci,D2N123,[doctor] so tyler is a 56 -year-old male who p...,SUBJECTIVE\n\nDifficulty swallowing. Tyler Gre...,[3207],[prescribed],[SUBJECTIVE\n\nDifficulty swallowing. Tyler Gr...,[Prilosec 20 mg once a day.]
11,36,aci,D2N124,[doctor] so jerry is a 45 -year-old male who c...,CHIEF COMPLAINT\n\nRight ankle injury.\n\nHIST...,[1951],[prescribe],[CHIEF COMPLAINT\n\nRight ankle injury.\n\nHIS...,[meloxicam to reduce swelling.]
12,39,aci,D2N127,[doctor] hey brandon you know glad to see you ...,CHIEF COMPLAINT\n\nNeck pain.\n\nHISTORY OF PR...,"[680, 2032]","[prescribed, prescribed]",[CHIEF COMPLAINT\n\nNeck pain.\n\nHISTORY OF P...,"[fentanyl; however, he has not received a pres..."

In [ ]:
# manually dropping instances where query words werent followed by drug names (will add this to initial filter rule)
filtered_df = filtered_df.drop(index=[2, 7])
filtered_df

,index,dataset,encounter_id,dialogue,note,match_indices,matched_words,truncated_notes,deleted_first_sentences
0,5,virtassist,D2N093,[doctor] hey lawrence . how are you ?\n[patien...,CHIEF COMPLAINT\n\nShortness of breath.\n\nHIS...,[2878],[Initiate],[CHIEF COMPLAINT\n\nShortness of breath.\n\nHI...,[Lasix 40 mg a day.]
1,7,virtassist,D2N095,"[doctor] hi , cheryl . how are you ?\n[patient...",CHIEF COMPLAINT\n\nBack pain.\n\nHISTORY OF PR...,[2154],[initiate],[CHIEF COMPLAINT\n\nBack pain.\n\nHISTORY OF P...,[meloxicam 15 mg once daily.]
3,17,virtscribe,D2N105,[doctor] patient's name is diana scott . date ...,CHIEF COMPLAINT\n\nHeart murmur.\n\nHISTORY OF...,[815],[prescribed],[CHIEF COMPLAINT\n\nHeart murmur.\n\nHISTORY O...,[pain medicine.]
4,18,aci,D2N106,[doctor] hey charles i'm using this cool new r...,CHIEF COMPLAINT\n\nShortness of breath.\n\nHIS...,"[506, 1898]","[prescribed, prescribed]",[CHIEF COMPLAINT\n\nShortness of breath.\n\nHI...,"[an inhaler, which he uses when his symptoms a..."
5,20,aci,D2N108,[doctor] hey gregory good to see you today so ...,CHIEF COMPLAINT\n\nRight foot ulcer.\n\nHISTOR...,[441],[prescribed],[CHIEF COMPLAINT\n\nRight foot ulcer.\n\nHISTO...,"[antibiotics, however, he has not started them..."
6,22,aci,D2N110,[doctor] okay hi wayne well i understand you'r...,HISTORY OF PRESENT ILLNESS\n\nWayne Jenkins is...,[2545],[prescribed],[HISTORY OF PRESENT ILLNESS\n\nWayne Jenkins i...,[a collagenase ointment to be applied to the w...
8,31,aci,D2N119,[doctor] hey betty how are you doing\n[patient...,CHIEF COMPLAINT\n\nAsthma.\n\nMEDICAL HISTORY\...,[1708],[Prescribed],[CHIEF COMPLAINT\n\nAsthma.\n\nMEDICAL HISTORY...,[provided for Flovent 110 mcg 1 puff twice per...
9,32,aci,D2N120,[doctor] hello larry how are you doing today\n...,HISTORY OF PRESENT ILLNESS\n\nLarry Garcia is ...,[943],[prescribed],[HISTORY OF PRESENT ILLNESS\n\nLarry Garcia is...,"[pain medications, however they only provided ..."
10,35,aci,D2N123,[doctor] so tyler is a 56 -year-old male who p...,SUBJECTIVE\n\nDifficulty swallowing. Tyler Gre...,[3207],[prescribed],[SUBJECTIVE\n\nDifficulty swallowing. Tyler Gr...,[Prilosec 20 mg once a day.]
11,36,aci,D2N124,[doctor] so jerry is a 45 -year-old male who c...,CHIEF COMPLAINT\n\nRight ankle injury.\n\nHIST...,[1951],[prescribe],[CHIEF COMPLAINT\n\nRight ankle injury.\n\nHIS...,[meloxicam to reduce swelling.]
12,39,aci,D2N127,[doctor] hey brandon you know glad to see you ...,CHIEF COMPLAINT\n\nNeck pain.\n\nHISTORY OF PR...,"[680, 2032]","[prescribed, prescribed]",[CHIEF COMPLAINT\n\nNeck pain.\n\nHISTORY OF P...,"[fentanyl; however, he has not received a pres..."

In [17]:
from google import genai
from google.genai import types

GEMINI_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=";
GEMINI_API_KEY="AIzaSyDV4odoZDhF3aUNvLgpkNriDIzQ2qPBQOo"

def get_completions_gemini(note):
    client = genai.Client(api_key=GEMINI_API_KEY)
    
    prompt = "Complete the sentence in this truncated clinical note.\nNote:\n" + note

    response = client.models.generate_content(
        model="gemini-2.0-flash", contents=prompt
    )
    return response.text

In [9]:
from transformers import AutoTokenizer, AutoModel
import torch

def get_completions_clinicalbert(note):
    tokenizer = AutoTokenizer.from_pretrained("medicalai/ClinicalBERT")
    model = AutoModel.from_pretrained("medicalai/ClinicalBERT")

    text = "Complete the sentence in this truncated clinical note.\nNote:\n" + note
    inputs = tokenizer(text, return_tensors="pt")

    with torch.no_grad():
        outputs = model(**inputs, output_hidden_states=True)

    # Get all hidden states
    hidden_states = outputs.hidden_states

    # Example: CLS token from final layer
    cls_vector = hidden_states[-1][0, 0, :]  # shape: (hidden_size,)
    print(cls_vector.shape)
    print(outputs)

None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

ModuleNotFoundError: No module named 'torch'

In [ ]:
# check if model completion contains the expected next word (drug name) anywhere 
def compare_completion(truncateds, deleted_sentences):
    completions = []
    comparisons = []

    for trunc_list, deleted_list in zip(truncateds, deleted_sentences):
        row_completions = []
        row_comparisons = []

        for trunc, deleted in zip(trunc_list, deleted_list):
            if not trunc:
                row_completions.append('')
                row_comparisons.append(False)
                continue
            
            completion = get_completions_gemini(trunc)

            # Extract first word of deleted part
            first_word_match = re.match(r'\b(\w+)\b', deleted)
            first_word = first_word_match.group(1).lower() if first_word_match else ''

            # Check if completion contains the word
            match_found = first_word in completion.lower()

            row_completions.append(completion)
            row_comparisons.append(match_found)

        completions.append(row_completions)
        comparisons.append(row_comparisons)

    return completions, comparisons

In [20]:
filtered_df['completions'], filtered_df['matches_first_word'] = compare_completion(
    filtered_df['truncated_notes'],
    filtered_df['deleted_first_sentences']
)
filtered_df

,index,dataset,encounter_id,dialogue,note,match_indices,matched_words,truncated_notes,deleted_first_sentences,completions,matches_first_word
0,5,virtassist,D2N093,[doctor] hey lawrence . how are you ?\n[patien...,CHIEF COMPLAINT\n\nShortness of breath.\n\nHIS...,[2878],[Initiate],[CHIEF COMPLAINT\n\nShortness of breath.\n\nHI...,[Lasix 40 mg a day.],[**• Medical Treatment: Initiate a trial of or...,[False]
1,7,virtassist,D2N095,"[doctor] hi , cheryl . how are you ?\n[patient...",CHIEF COMPLAINT\n\nBack pain.\n\nHISTORY OF PR...,[2154],[initiate],[CHIEF COMPLAINT\n\nBack pain.\n\nHISTORY OF P...,[meloxicam 15 mg once daily.],[Ms. Ramirez is a 34-year-old female with a pa...,[False]
3,17,virtscribe,D2N105,[doctor] patient's name is diana scott . date ...,CHIEF COMPLAINT\n\nHeart murmur.\n\nHISTORY OF...,[815],[prescribed],[CHIEF COMPLAINT\n\nHeart murmur.\n\nHISTORY O...,[pain medicine.],[...**Naproxen for the leg pain.**\n],[True]
4,18,aci,D2N106,[doctor] hey charles i'm using this cool new r...,CHIEF COMPLAINT\n\nShortness of breath.\n\nHIS...,"[506, 1898]","[prescribed, prescribed]",[CHIEF COMPLAINT\n\nShortness of breath.\n\nHI...,"[an inhaler, which he uses when his symptoms a...","[... **oral steroids with improvement.**\n, **...","[False, False]"
5,20,aci,D2N108,[doctor] hey gregory good to see you today so ...,CHIEF COMPLAINT\n\nRight foot ulcer.\n\nHISTOR...,[441],[prescribed],[CHIEF COMPLAINT\n\nRight foot ulcer.\n\nHISTO...,"[antibiotics, however, he has not started them...",[... oral antibiotics without improvement.\n],[True]
6,22,aci,D2N110,[doctor] okay hi wayne well i understand you'r...,HISTORY OF PRESENT ILLNESS\n\nWayne Jenkins is...,[2545],[prescribed],[HISTORY OF PRESENT ILLNESS\n\nWayne Jenkins i...,[a collagenase ointment to be applied to the w...,[I have prescribed **topical silver sulfadiazi...,[True]
8,31,aci,D2N119,[doctor] hey betty how are you doing\n[patient...,CHIEF COMPLAINT\n\nAsthma.\n\nMEDICAL HISTORY\...,[1708],[Prescribed],[CHIEF COMPLAINT\n\nAsthma.\n\nMEDICAL HISTORY...,[provided for Flovent 110 mcg 1 puff twice per...,"[Prescribed **inhaled corticosteroid, one puff...",[False]
9,32,aci,D2N120,[doctor] hello larry how are you doing today\n...,HISTORY OF PRESENT ILLNESS\n\nLarry Garcia is ...,[943],[prescribed],[HISTORY OF PRESENT ILLNESS\n\nLarry Garcia is...,"[pain medications, however they only provided ...","[In the past, he has attended physical therapy...",[False]
10,35,aci,D2N123,[doctor] so tyler is a 56 -year-old male who p...,SUBJECTIVE\n\nDifficulty swallowing. Tyler Gre...,[3207],[prescribed],[SUBJECTIVE\n\nDifficulty swallowing. Tyler Gr...,[Prilosec 20 mg once a day.],[**Prilosec 20 mg daily for possible reflux.**\n],[True]
11,36,aci,D2N124,[doctor] so jerry is a 45 -year-old male who c...,CHIEF COMPLAINT\n\nRight ankle injury.\n\nHIST...,[1951],[prescribe],[CHIEF COMPLAINT\n\nRight ankle injury.\n\nHIS...,[meloxicam to reduce swelling.],[...**him pain medication and non-weight beari...,[False]
12,39,aci,D2N127,[doctor] hey brandon you know glad to see you ...,CHIEF COMPLAINT\n\nNeck pain.\n\nHISTORY OF PR...,"[680, 2032]","[prescribed, prescribed]",[CHIEF COMPLAINT\n\nNeck pain.\n\nHISTORY OF P...,"[fentanyl; however, he has not received a pres...","[He was prescribed **opioid medications.**\n, ...","[False, False]"

In [21]:
for index, row in filtered_df.iterrows():
    print("-----",index,"--------")
    completions = row['completions']
    deletions = row['deleted_first_sentences']
    matches = row['matches_first_word']
    for c, d, m in zip(completions, deletions, matches):
        print("completion: ", c)
        print("deletion: ", d)
        print("match: ", m)

----- 0 --------
completion:  **• Medical Treatment: Initiate a trial of oral diuretic therapy.**

deletion:  Lasix 40 mg a day.
match:  False
----- 1 --------
completion:  Ms. Ramirez is a 34-year-old female with a past medical history significant for hypertension, who presents today with back pain.

Back pain.
*   Medical Reasoning: She experienced a spasm-like pain in her back while walking approximately 6 days ago. She has also been lifting weights recently. Her lumbar spine x-ray was unremarkable and her recent labs were normal. I believe she has a lumbar strain.
*   Medical Treatment: We will initiate **a course of physical therapy, continue with ibuprofen as needed, and encourage continued home heat application. We will also discuss proper lifting techniques to minimize future strain.**

deletion:  meloxicam 15 mg once daily.
match:  False
----- 3 --------
completion:  ...**Naproxen for the leg pain.**

deletion:  pain medicine.
match:  True
----- 4 --------
completion:  ... **oral steroids with improvement.**

deletion:  an inhaler, which he uses when his symptoms are present.
match:  False
completion:  **inhaled corticosteroids to use daily.**

deletion:  the patient Singulair 10 mg to be taken once daily.
match:  False
----- 5 --------
completion:  ... oral antibiotics without improvement.

deletion:  antibiotics, however, he has not started them yet and does not recall the name of the medication.
match:  True
----- 6 --------
completion:  I have prescribed **topical silver sulfadiazine and a daily dressing change.**

deletion:  a collagenase ointment to be applied to the wound 1 time daily and instructed him to cover with a dry sterile dressing.
match:  True
----- 8 --------
completion:  Prescribed **inhaled corticosteroid, one puff daily**.

deletion:  provided for Flovent 110 mcg 1 puff twice per day.
match:  False
----- 9 --------
completion:  In the past, he has attended physical therapy. The patient has also been prescribed **NSAIDs and muscle relaxants with minimal relief.**

deletion:  pain medications, however they only provided temporary relief.
match:  False
----- 10 --------
completion:  **Prilosec 20 mg daily for possible reflux.**

deletion:  Prilosec 20 mg once a day.
match:  True
----- 11 --------
completion:  ...**him pain medication and non-weight bearing instructions, and he is scheduled for surgery.**

deletion:  meloxicam to reduce swelling.
match:  False
----- 12 --------
completion:  He was prescribed **opioid medications.**

deletion:  fentanyl; however, he has not received a prescription for several weeks.
match:  False
completion:  ...**ibuprofen 800mg TID PRN pain.**

deletion:  the patient Robaxin 1500 mg every 6 to 8 hours to treat his pain.
match:  False